### ISSUE TITLE
Make available through FlatHub

### ISSUE THREAD

**Issue by aha999** [PolyMeilex/Neothesia#10]
It would be great if Neothesia would be available as a [flatpak](https://flatpak.org/) on [FlatHub](https://flathub.org/), so it could be easily installed and updated through app stores on Linux.

- [Flatpak docs starter guide](https://docs.flatpak.org/en/latest/first-build.html)

**Comment by PolyMeilex** [comment]
https://flathub.org/apps/details/com.github.polymeilex.neothesia

**Comment by cazzoo** [comment]
False linking
