### ISSUE TITLE
text is rendered as rectangular shapes

### ISSUE THREAD

**Issue by gibso** [PolyMeilex/Neothesia#168]
I can not read the text on my end. This is the latest release for ubuntu that I just downloded (v0.2.1).

![image](https://github.com/PolyMeilex/Neothesia/assets/17612282/ebb54a35-03cd-42a4-bc36-49daf779afbf)

I am running this on Ubuntu 22.04.4 LTS. The version before (v0.2.0) works actually fine.

**Comment by PolyMeilex** [comment]
This was most likely fixed by prebunding a font, rather than using system font, should be part of the next releasse.
