### ISSUE TITLE
Cannot open on Mac.

### ISSUE THREAD

**Issue by vanakard** [PolyMeilex/Neothesia#18]
Crashes upon open in Catalina.

**Comment by PolyMeilex** [comment]
yep, it's probably because of this https://github.com/gfx-rs/naga/issues/1490

**Comment by PolyMeilex** [comment]
You could try an older version of Neothesia, when naga was not used.

**Comment by vanakard** [comment]
> You could try an older version of Neothesia, when naga was not used.

Thank you! v0.0.9 works on Catalina well!

**Comment by PolyMeilex** [comment]
This was fixed a few versions ago
