### ISSUE TITLE
make it more obvious how to do pace changes

### ISSUE THREAD

**Issue by alexanderadam** [PolyMeilex/Neothesia#190]
I somehow wasn't aware of how to do this, which is why I opened #188.
But maybe it would be possible to make it more obvious for folks that are new to Neothesia.

**Comment by PolyMeilex** [comment]
It's already planned, but thanks for opening the issue, it will be easier to track this.

Current design for playback speed controls looks like this:

![Frame 32](https://github.com/user-attachments/assets/93cb6a6c-c01d-455d-90db-b51785753d41)
