### ISSUE TITLE
Learning mode

### ISSUE THREAD

**Issue by alexanderadam** [PolyMeilex/Neothesia#191]
It would be great if there would be a learning mode that stops the game until the right key was pressed.

Similar to what [Openthesia](https://github.com/ImAxel0/Openthesia?tab=readme-ov-file#openthesia--) has:

https://youtu.be/PMJwmzkHlSo?t=74

Also it shows the keys in the blocks in that mode (although I'm not sure what it does on short key tippings):

![image](https://github.com/user-attachments/assets/63fdb2bd-a760-4001-931e-e1a395900635)

**Comment by PolyMeilex** [comment]
It already has one, in track selection screen press play along, or just set whichever tracks you want to human player.
