### ISSUE TITLE
neothesia-cli.exe can't start because DLLs are missing

### ISSUE THREAD

**Issue by Boscop** [PolyMeilex/Neothesia#199]
On Win 11, neothesia-cli.exe can't start because DLLs are missing:

avformat-60.dll
avcodec-60.dll 
avutil-58.dll 
swscale-7.dll

Where should I get them from? 🙂

I have ffmpeg 7.0.2 installed via scoop btw.

**Comment by PolyMeilex** [comment]
Tbh, I have no idea, I have never tested that build as I don't even know how one wold install ffmpeg on windows.
But in CI I have this random copy-pasted snippet of code that makes the build work somehow (the FFMPEG_DOWNLOAD_URL env variable is equal to https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z):
https://github.com/PolyMeilex/Neothesia/blob/29887ce6b8dbec54d337db1f11125b0585df2936/.github/actions/windows-recorder/action.yml#L9

Perhaps that will help somehow.
(also you could try to copy-paste the neothesia.exe to the DLLs `bin` folder from https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z :smile: )

Also maybe a newer build from master (that was built against 7.0.2 will work):
[windows-recorder-artifact.zip](https://github.com/user-attachments/files/17006196/windows-recorder-artifact.zip)

**Comment by Boscop** [comment]
Thanks, it works after I copied the DLLs from that 7z :)
