### ISSUE TITLE
MIDI Controller input not detected

### ISSUE THREAD

**Issue by zaakirio** [PolyMeilex/Neothesia#22]
Hi,

Is there support for MIDI Controller Keyboard? I wish to use the keys on my midi controller to interact with the midi in the program- is this possible? For reference, I am trying to achieve this with Arturia MiniLab MK2

**Comment by PolyMeilex** [comment]
It is not implemented at the moment, we only support midi-out as of now. There is some work on midi-in / play-along, but nothing usable as of now.

**Comment by PolyMeilex** [comment]
Midi input was added a few versions ago

**Comment by zaakirio** [comment]
Yay! 🎆
