### ISSUE TITLE
[Feature request] Track selection

### ISSUE THREAD

**Issue by Salvatos** [PolyMeilex/Neothesia#24]
Thank you for making this! An option to turn off certain tracks would be great for midi files that include so many instruments that it’s impossible to follow just one :)

**Comment by Salvatos** [comment]
It just occurred to me that I can easily remove midi tracks in MuseScore and export the desired variants, so here’s a quick guide in case others were hoping for the same feature. MuseScore is also free and open source :)

1. Open your midi file in MuseScore.
1. The bottom middle panel should show you all midi tracks. Uncheck the ones you want to remove and click the Import button. The sheet music will reload without the unwanted tracks and you can preview the remaining ones. You can press Space or the Play button at the top to hear the song if your output is correctly configured.
1. Alternatively, press I to open the Instruments window (or go to Edit > Instruments), select each instrument you want to remove and click the Remove button after each selection, then click OK.
1. Once satisfied with your changes, go to File > Export and select the MIDI format before saving the file to the desired location.

Hope that helps!

**Comment by PolyMeilex** [comment]
Got some initial design work for this going, not entirely happy with track selection design so far, but it's a decent-ish starting point.

### Track selection
![Tracks](https://github.com/PolyMeilex/Neothesia/assets/20758186/3813c2aa-eb41-4f74-bdc7-c51c28ce21a2)

### Track color picker
![Color picker](https://github.com/PolyMeilex/Neothesia/assets/20758186/7e7639ab-6839-44e6-937a-4d0024cffc8d)

### Custom track color picker
![Custom track color picker](https://github.com/PolyMeilex/Neothesia/assets/20758186/06ffbb3d-9879-4ef1-8709-99eed81a710c)

**Comment by Salvatos** [comment]
Thank you for looking into it! I like the look of it already.

Something I didn’t mention in the OP: it would also be great if we can include tracks for playback but not require them to be played to progress in PlayAlong mode (say you want to hear the accompaniment but not practice it yet). I play very occasionally so I tend to stick to the right hand so I don’t have as much to learn at once :)

**Comment by PolyMeilex** [comment]
Oh yeha, I compleatly forgot about the need for that, will try to include that as well, thanks!

**Comment by PolyMeilex** [comment]
This design should handle both cases, and the look is slowly improving as well IMO.

And I've gotta say, this tracks color schema provided by @othello777 looks really dope in this setting :rocket: it accompaniments the neon vibe that I'm going for really well.

![Tracks v2](https://github.com/PolyMeilex/Neothesia/assets/20758186/eae8fce9-353a-4dfe-8037-50db585c0198)

(That's enough spam from me for today, I will now proceed to shut up until I have implementation for this going 😅)

**Comment by Salvatos** [comment]
Ooooh yes I like the toggle, very clear and easy to parse at a glance once you’re familiar with it :)

Don’t worry about spamming me, it’s great to see the progress. In the meantime, time to hunt for midi tracks of all the songs I want to play that aren’t mainstream enough to be on YouTube!

**Comment by othello777** [comment]
would it be possible to include `Program Change Event` passthrough with this update too? (that way the instruments aren't always just switched to grand piano on the output)

**Comment by PolyMeilex** [comment]
passthrough? Isn't this already the case?

https://github.com/PolyMeilex/Neothesia/assets/20758186/7af0d69e-3e9b-4f13-ab62-24f0fbf96937

It's not fully working tho, for example rewinding can cause program change events to be skipped, but that's a separate issue.

**Comment by othello777** [comment]
oh woah, ig it was fixed at some point. I've really gotta keep up. sorry for sidetracking this lol

**Comment by PolyMeilex** [comment]
Already implemented on `master`, will be part of 0.2 release

**Comment by PolyMeilex** [comment]
Test binaries from master that contain this feature:
[ubuntu-artifact.zip](https://github.com/PolyMeilex/Neothesia/files/13693625/ubuntu-artifact.zip)
[windows-artifact.zip](https://github.com/PolyMeilex/Neothesia/files/13693626/windows-artifact.zip)
[macos-artifact.zip](https://github.com/PolyMeilex/Neothesia/files/13693627/macos-artifact.zip)
