### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Youras** [PolyMeilex/Neothesia#30]
When I run the app, choose a midi and play it,  I don't get any sound. Apart from https://github.com/PolyMeilex/Neothesia/issues/6 the visual part works just fine, just no audio.

On the sound settings of ubuntu I see ALSA plug-in [neothesia] so I would expect some sound. But nothing...

My ALSA usually works, when I run for testing `aplay /usr/share/sounds/alsa/Front_Center.wav` everything seems ok.

Any idea why I get no sound from neothesia?
I also tried different midi files and soundfonts, but no change.

OS: Ubuntu 20.04
I downloaded the 0.0.14. release (https://github.com/PolyMeilex/Neothesia/releases/download/v0.0.14/ubuntu-artifact.zip)

Many thanks in advance

**Comment by Youras** [comment]
okay I got it solved now, I didn't know that you always HAVE to pass a soundfont. And the one soundfont that I had was the problem.

**Comment by PolyMeilex** [comment]
You can put default.sf2 in .config/neothesia, if you are tired of picking the font btw

**Comment by Tridu33** [comment]
> You can put default.sf2 in .config/neothesia, if you are tired of picking the font btw

what do you mean? Is the absolute path `/app/share/neothesia/default.sf2` or `${HOME}/.config/default.sf2` in `fn xdg_config()` ?

**Comment by PolyMeilex** [comment]
First we check [XDG_CONFIG_HOME/neothesia](https://github.com/PolyMeilex/Neothesia/blob/c53e998a85753fc737d3e390adfb9d79a4f83f3b/neothesia-core/src/utils/resources.rs#L22)
If that fails, we check [/share system directory](https://github.com/PolyMeilex/Neothesia/blob/c53e998a85753fc737d3e390adfb9d79a4f83f3b/neothesia-core/src/utils/resources.rs#L34)
If that fails, we check [/app/share/neothesia/default.sf2](https://github.com/PolyMeilex/Neothesia/blob/c53e998a85753fc737d3e390adfb9d79a4f83f3b/neothesia-core/src/utils/resources.rs#L40) to find prebundeled sf2 that flatpak build ships.

So the user facing way to do this is via `$XDG_CONFIG_HOME/neothesia`
