### ISSUE TITLE
failed to compile the exe from source code since " failed to run custom build command for `ffmpeg-sys v4.3.3`"

### ISSUE THREAD

**Issue by Tridu33** [PolyMeilex/Neothesia#33]
run `cargo build --release --no-default-features --features record`, it turns:
```bash
   Compiling ffmpeg-sys v4.3.3
error: failed to run custom build command for `ffmpeg-sys v4.3.3`

Caused by:
  process didn't exit successfully: `C:\tridu33\mymidi\ReactMidiPlayers\Neothesia\target\release\build\ffmpeg-sys-84f31d4dbb84e5a1\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-search=native=C:\tridu33\mymidi\ReactMidiPlayers\Neothesia\target\release\build\ffmpeg-sys-92a0d0343867013d\out\dist\lib
  cargo:rustc-link-lib=static=avcodec
  cargo:rustc-link-lib=static=avformat
  cargo:rustc-link-lib=static=avutil
  cargo:rustc-link-lib=static=swscale

  --- stderr
  Using stack size: Ok(3145728)
  Cloning into 'ffmpeg-4.3'...
Updating files: 100% (7327/7327), done.
  thread 'ffmpg-sys-build' panicked at '"C:\\tridu33\\mymidi\\ReactMidiPlayers\\Neothesia\\target\\release\\build\\ffmpeg-sys-92a0d0343867013d\\out\\ffmpeg-4.3\\configure" "--prefix=C:\\tridu33\\mymidi\\ReactMidiPlayers\\Neothesia\\target\\release\\build\\ffmpeg-sys-92a0d0343867013d\\out\\dist" "--enable-debug" "--disable-stripping" "--disable-optimizations" "--enable-static" "--disable-shared" "--enable-pic" "--disable-autodetect" "--disable-programs" "--disable-gpl" "--disable-version3" "--disable-nonfree" "--enable-avcodec" "--disable-avdevice" "--disable-avfilter" "--enable-avformat" "--disable-avresample" "--disable-postproc" "--disable-swresample" "--enable-swscale" failed', C:\Users\tridu33\.cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-4.3.3\build.rs:337:29
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', C:\Users\tridu33\.cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-4.3.3\build.rs:629:10

```

**Comment by PolyMeilex** [comment]
Looks like it failed to build ffmpeg from source (perhaps you don't have C build tools installed)

If you have ffmpeg installed you can also try to simply disable the build step for ffmpeg, by removing "build-ffmpeg" from the list here:
https://github.com/PolyMeilex/Neothesia/blob/master/Cargo.toml#L29

**Comment by Tridu33** [comment]
> Looks like it failed to build ffmpeg from source (perhaps you don't have C build tools installed)
> 
> If you have ffmpeg installed you can also try to simply disable the build step for ffmpeg, by removing "build-ffmpeg" from the list here: https://github.com/PolyMeilex/Neothesia/blob/master/Cargo.toml#L29

it seems mpeg_encoder need ffmpeg-sys in `Cargo.lock` like this, how can i just change `record = ["mpeg_encoder", "build-ffmpeg"]` in [`Cargo.toml` line 29](https://github.com/PolyMeilex/Neothesia/blob/master/Cargo.toml#L29) to `record = ["mpeg_encoder"]`:
```bash
[[package]]
name = "mpeg_encoder"
version = "0.2.1"
source = "git+https://github.com/PolyMeilex/mpeg_encoder_next.git#e366f9ec267ca2265b0ddebfdab196c7b675ae9f"
dependencies = [
 "ffmpeg-sys",
]
```

**Comment by Tridu33** [comment]
i give up to compile it in windows, but how to debug rust programs by IDE in windows WSL(ubuntu)?
```bash
/NeothesiaWSL/Neothesia$ sudo apt-get install yasm -y
/NeothesiaWSL/Neothesia$ cargo build --release --no-default-features --features record
   Compiling ffmpeg-sys v4.3.3
   Compiling mpeg_encoder v0.2.1 (https://github.com/PolyMeilex/mpeg_encoder_next.git#e366f9ec)
   Compiling neothesia v0.0.15 (/mnt/c/tridu33/mymidi/ReactMidiPlayers/NeothesiaWSL/Neothesia)
    Finished release [optimized] target(s) in 50.68s
```

**Comment by Tridu33** [comment]
https://github.com/microsoft/wslg/issues/420
```bash
$ ./neothesia-cli-wsl ./test.mid
error: XDG_RUNTIME_DIR not set in the environment.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[2023-02-12T09:26:41Z ERROR neothesia::output_manager] MIDI support could not be initialized
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitError', src/input_manager/mod.rs:11:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Tridu33** [comment]
it seems the abandoned [ffmpeg-sys](https://github.com/meh/rust-ffmpeg-sys) crate is replaced by this crate as [ffmpeg-sys-next](https://crates.io/crates/ffmpeg-sys-next) on crates.io as [here](https://lib.rs/crates/ffmpeg-sys-next) says. 
So i failed to compil the executable file under `wsl-ubuntu` and 
` MINGW64_NT-10.0-22621 tridu33 3.4.5.x86_64 2023-01-20 09:17 UTC x86_64 Msys`, because:


`[Neothesia](https://github.com/PolyMeilex/Neothesia)`=>` [mpeg_encoder_next](https://github.com/PolyMeilex/mpeg_encoder_next)` =>  `ffmpeg-sys` is abandoned and replaced by [ffmpeg-sys-next](https://crates.io/crates/ffmpeg-sys-next)

**Comment by PolyMeilex** [comment]
How about now? Updated mpeg_encoder_next to use ffmepg-sys-next, updated Neothesia as well.

**Comment by Tridu33** [comment]
> How about now? Updated mpeg_encoder_next to use ffmepg-sys-next, updated Neothesia as well.

Fine! it's done! Thank you so much!
