### ISSUE TITLE
Key visualizations not loading

### ISSUE THREAD

**Issue by kabyanil** [PolyMeilex/Neothesia#34]
Hi, When I load the midi file, the key visualizations are not loading. All I can see is a black screen. I can still connect to my keybaord  and play the keys though. I'm using Mac OS Monterey 12.6.3.

<img width="1087" alt="Screenshot 2023-02-17 at 10 45 16 AM" src="https://user-images.githubusercontent.com/24878109/219555784-da9252e7-a966-4a02-b476-8a1345de0ef6.png">

**Comment by PolyMeilex** [comment]
We had similar issue recently, related to running on displays that use scaling. Could you try this build https://github.com/PolyMeilex/Neothesia/actions/runs/4168923481

**Comment by kabyanil** [comment]
It's working now. Thanks a lot.
