### ISSUE TITLE
Rewind doesn't seem to work

### ISSUE THREAD

**Issue by David-Else** [PolyMeilex/Neothesia#92]
I can play along, when I don't press a note on time the music stops, when I press it then it continues to the next note... but how do I go backwards and rewind to practice a section again? I press the right cursor and it fast forwards, but the left seems to do nothing? Sorry if I missed something basic, thanks!

PS Look forward to the new version on Flathub, seems there has been quite a bit of work done since the last one.

**Comment by PolyMeilex** [comment]
It's a bug in play along mode, the app is waiting for all required notes to be pressed and because of that it can't rewind, should be easy to fix.

**Comment by PolyMeilex** [comment]
Hopefully this fixes the problem (just a binary dump as I don't have flatpak CI setup yet):
[linux-artifact.zip](https://github.com/PolyMeilex/Neothesia/files/12754569/linux-artifact.zip)

**Comment by David-Else** [comment]
Thanks for the quick fix! I am trying not to mess with my system config, so I will wait to test the fix when the flatpak is released. Do you think that will be soon(ish)?
